### ISSUE TITLE
Create environment

### ISSUE THREAD

**Issue by MirandaBiel** [phuselab/pyVHR#90]
Hi, I'm trying to create an environment with the command conda env create --file https://raw.githubusercontent.com/phuselab/pyVHR/pyVHR_CPU/pyVHR_CPU_env.yml, but I believe the pyVHR_CPU_env.yml specs are out of date, anyone can you help me?  the first error is that there is no mediapipe version 0.8.8.1

I've already tried both the GPU version and the CPU version, both give errors

**Comment by Pablo-Arias** [comment]
Same problem here, did you find any resolution?

**Comment by MirandaBiel** [comment]
I gave up and started doing my own methods 😅

**Comment by gauthier-th** [comment]
Just update the version of mediapipe to `0.8.11` in a new `pyVHR_env.yml` file on your computer, and then rerun the command with the local file :

```bash
conda env create --file ./pyVHR_env.yml
```

pyVHR_env.yml content:
```yml
name: pyvhr
channels:
  - pytorch
  - rapidsai
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3
  - cusignal=21.08.00
  - hdf5=1.10.6
  - pip=21.3.1
  - pytables=3.6.1
  - pytorch=1.10.0
  - pytorch-mutex=1.0
  - python=3.9.7
  - torchaudio=0.10.0
  - torchvision=0.11.1
  - pip:
    - asposestorage==1.0.2
    - autorank==1.1.1
    - biosppy==0.7.3
    - ipython==7.28.0
    - ipywidgets==7.6.5
    - lmfit==1.0.3
    - mediapipe==0.8.11
    - plotly==5.3.1
    - pybdf==0.2.5
    - PySimpleGUI==4.53.0
    - scikit_posthocs==0.6.7
    - scikit-image==0.18.3
    - tqdm==4.62.3
    - tensorflow==2.5.0
```
